-- MySQL Script generated by MySQL Workbench
-- 04/28/15 15:22:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Information` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Information` (
  `idInformation` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Nb_Max_Player` INT NULL,
  `Description` VARCHAR(45) NULL,
  `Classification` VARCHAR(45) NULL,
  PRIMARY KEY (`idInformation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Editeur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Editeur` (
  `idEditeur` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idEditeur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editeurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Editeurs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Editeurs` (
  `idEditeurs` INT NOT NULL AUTO_INCREMENT,
  `idInformation` INT NOT NULL,
  `idEditeur` INT NOT NULL,
  PRIMARY KEY (`idEditeurs`),
  INDEX `fk_Editeurs_Information_idx` (`idInformation` ASC),
  INDEX `fk_Editeurs_Editeur1_idx` (`idEditeur` ASC),
  CONSTRAINT `fk_Editeurs_Information`
    FOREIGN KEY (`idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Editeurs_Editeur1`
    FOREIGN KEY (`idEditeur`)
    REFERENCES `mydb`.`Editeur` (`idEditeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Developpeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Developpeur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Developpeur` (
  `idDeveloppeur` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idDeveloppeur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Developpeurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Developpeurs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Developpeurs` (
  `idDeveloppeurs` INT NOT NULL AUTO_INCREMENT,
  `idDeveloppeur` INT NOT NULL,
  `idInformation` INT NOT NULL,
  PRIMARY KEY (`idDeveloppeurs`),
  INDEX `fk_Developpeurs_Developpeur1_idx` (`idDeveloppeur` ASC),
  INDEX `fk_Developpeurs_Information1_idx` (`idInformation` ASC),
  CONSTRAINT `fk_Developpeurs_Developpeur1`
    FOREIGN KEY (`idDeveloppeur`)
    REFERENCES `mydb`.`Developpeur` (`idDeveloppeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Developpeurs_Information1`
    FOREIGN KEY (`idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pays` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pays` (
  `idPays` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idPays`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sortie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sortie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sortie` (
  `idSortie` INT NOT NULL AUTO_INCREMENT,
  `idPays` INT NOT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`idSortie`),
  INDEX `fk_Sortie_Pays1_idx` (`idPays` ASC),
  CONSTRAINT `fk_Sortie_Pays1`
    FOREIGN KEY (`idPays`)
    REFERENCES `mydb`.`Pays` (`idPays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sorties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sorties` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sorties` (
  `idSorties` INT NOT NULL AUTO_INCREMENT,
  `idInformation` INT NOT NULL,
  `idSortie` INT NOT NULL,
  PRIMARY KEY (`idSorties`),
  INDEX `fk_Sorties_Sortie1_idx` (`idSortie` ASC),
  INDEX `fk_Sorties_Information1_idx` (`idInformation` ASC),
  CONSTRAINT `fk_Sorties_Sortie1`
    FOREIGN KEY (`idSortie`)
    REFERENCES `mydb`.`Sortie` (`idSortie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sorties_Information1`
    FOREIGN KEY (`idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Genres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Genres` (
  `idGenres` INT NOT NULL AUTO_INCREMENT,
  `idInformation` INT NOT NULL,
  `Nom` ENUM('MMORPG','Role','FPS') NULL,
  PRIMARY KEY (`idGenres`),
  INDEX `fk_Genres_Information1_idx` (`idInformation` ASC),
  CONSTRAINT `fk_Genres_Information1`
    FOREIGN KEY (`idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Themes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Themes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Themes` (
  `idThemes` INT NOT NULL AUTO_INCREMENT,
  `idInformation` INT NOT NULL,
  `Nom` ENUM('Course','Aventure','Fuck') NULL,
  PRIMARY KEY (`idThemes`),
  INDEX `fk_Themes_Information1_idx` (`idInformation` ASC),
  CONSTRAINT `fk_Themes_Information1`
    FOREIGN KEY (`idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Modes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Modes` (
  `idModes` INT NOT NULL AUTO_INCREMENT,
  `idInformation` INT NOT NULL,
  `Nom` ENUM('MultiJoueurs','Solo') NULL,
  PRIMARY KEY (`idModes`),
  INDEX `fk_Modes_Information1_idx` (`idInformation` ASC),
  CONSTRAINT `fk_Modes_Information1`
    FOREIGN KEY (`idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Supports` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Supports` (
  `idSupports` INT NOT NULL AUTO_INCREMENT,
  `idInformation` INT NOT NULL,
  `Nom` ENUM('PS4','XBOX','PC') NULL,
  PRIMARY KEY (`idSupports`),
  INDEX `fk_Supports_Information1_idx` (`idInformation` ASC),
  CONSTRAINT `fk_Supports_Information1`
    FOREIGN KEY (`idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Site` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Site` (
  `idSite` INT NOT NULL AUTO_INCREMENT,
  `idInformation` INT NOT NULL,
  `idPays` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idSite`),
  INDEX `fk_Site_Information1_idx` (`idInformation` ASC),
  INDEX `fk_Site_Pays1_idx` (`idPays` ASC),
  CONSTRAINT `fk_Site_Information1`
    FOREIGN KEY (`idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Site_Pays1`
    FOREIGN KEY (`idPays`)
    REFERENCES `mydb`.`Pays` (`idPays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ModeleEco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ModeleEco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ModeleEco` (
  `idModeleEco` INT NOT NULL AUTO_INCREMENT,
  `idInformation` INT NOT NULL,
  `Nom` ENUM('Achat','En Ligne') NULL,
  PRIMARY KEY (`idModeleEco`),
  INDEX `fk_ModeleEco_Information1_idx` (`idInformation` ASC),
  CONSTRAINT `fk_ModeleEco_Information1`
    FOREIGN KEY (`idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Image` (
  `idImage` INT NOT NULL AUTO_INCREMENT,
  `Format` VARCHAR(45) NULL,
  `Lien` VARCHAR(45) NULL,
  PRIMARY KEY (`idImage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entete` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entete` (
  `idEntete` INT NOT NULL AUTO_INCREMENT,
  `idImage` INT NOT NULL,
  `Auteur` VARCHAR(45) NULL,
  `Lien` VARCHAR(45) NULL,
  `Titre` VARCHAR(45) NULL,
  `Resume` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntete`),
  INDEX `fk_Entete_Image1_idx` (`idImage` ASC),
  CONSTRAINT `fk_Entete_Image1`
    FOREIGN KEY (`idImage`)
    REFERENCES `mydb`.`Image` (`idImage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plateform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Plateform` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Plateform` (
  `idPlateform` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlateform`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Test` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Test` (
  `idTest` INT NOT NULL AUTO_INCREMENT,
  `idEntete` INT NOT NULL,
  `Date_Publication` DATE NULL,
  `Type` VARCHAR(45) NULL,
  `idPlateform` INT NOT NULL,
  PRIMARY KEY (`idTest`),
  INDEX `fk_Test_Entete1_idx` (`idEntete` ASC),
  INDEX `fk_Test_Plateform1_idx` (`idPlateform` ASC),
  CONSTRAINT `fk_Test_Entete1`
    FOREIGN KEY (`idEntete`)
    REFERENCES `mydb`.`Entete` (`idEntete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_Plateform1`
    FOREIGN KEY (`idPlateform`)
    REFERENCES `mydb`.`Plateform` (`idPlateform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bloc` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bloc` (
  `idBloc` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Valeur` VARCHAR(45) NULL,
  `Content` VARCHAR(45) NULL,
  PRIMARY KEY (`idBloc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contenu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contenu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contenu` (
  `idContenu` INT NOT NULL AUTO_INCREMENT,
  `idTest` INT NOT NULL,
  `idBloc` INT NOT NULL,
  PRIMARY KEY (`idContenu`),
  INDEX `fk_Contenu_Test1_idx` (`idTest` ASC),
  INDEX `fk_Contenu_Bloc1_idx` (`idBloc` ASC),
  CONSTRAINT `fk_Contenu_Test1`
    FOREIGN KEY (`idTest`)
    REFERENCES `mydb`.`Test` (`idTest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contenu_Bloc1`
    FOREIGN KEY (`idBloc`)
    REFERENCES `mydb`.`Bloc` (`idBloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Note` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Note` (
  `idNote` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Valeur` VARCHAR(45) NULL,
  `Content` VARCHAR(45) NULL,
  PRIMARY KEY (`idNote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Notes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Notes` (
  `idNotes` INT NOT NULL AUTO_INCREMENT,
  `idNote` INT NOT NULL,
  `idTest` INT NOT NULL,
  PRIMARY KEY (`idNotes`),
  INDEX `fk_Notes_Note1_idx` (`idNote` ASC),
  INDEX `fk_Notes_Test1_idx` (`idTest` ASC),
  CONSTRAINT `fk_Notes_Note1`
    FOREIGN KEY (`idNote`)
    REFERENCES `mydb`.`Note` (`idNote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notes_Test1`
    FOREIGN KEY (`idTest`)
    REFERENCES `mydb`.`Test` (`idTest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jeu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jeu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Jeu` (
  `idJeu` INT NOT NULL AUTO_INCREMENT,
  `idInformation` INT NOT NULL,
  PRIMARY KEY (`idJeu`),
  INDEX `fk_Game_Information1_idx` (`idInformation` ASC),
  CONSTRAINT `fk_Game_Information1`
    FOREIGN KEY (`idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Media` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Media` (
  `idMedia` INT NOT NULL,
  `Titre` VARCHAR(45) NULL,
  `Lien` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Type` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Nb_Vue` VARCHAR(45) NULL,
  `Type_Media` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plateform_Media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Plateform_Media` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Plateform_Media` (
  `idPlateform_Media` INT NOT NULL AUTO_INCREMENT,
  `idPlateform` INT NOT NULL,
  `idMedia` INT NOT NULL,
  PRIMARY KEY (`idPlateform_Media`),
  INDEX `fk_Plateform_Media_Plateform1_idx` (`idPlateform` ASC),
  INDEX `fk_Plateform_Media_Media1_idx` (`idMedia` ASC),
  CONSTRAINT `fk_Plateform_Media_Plateform1`
    FOREIGN KEY (`idPlateform`)
    REFERENCES `mydb`.`Plateform` (`idPlateform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plateform_Media_Media1`
    FOREIGN KEY (`idMedia`)
    REFERENCES `mydb`.`Media` (`idMedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tags` (
  `idTags` INT NOT NULL AUTO_INCREMENT,
  `idTag` INT NOT NULL,
  `idMedia` INT NOT NULL,
  PRIMARY KEY (`idTags`),
  INDEX `fk_Tags_Tag1_idx` (`idTag` ASC),
  INDEX `fk_Tags_Media1_idx` (`idMedia` ASC),
  CONSTRAINT `fk_Tags_Tag1`
    FOREIGN KEY (`idTag`)
    REFERENCES `mydb`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tags_Media1`
    FOREIGN KEY (`idMedia`)
    REFERENCES `mydb`.`Media` (`idMedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JeuMedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JeuMedia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JeuMedia` (
  `idJeuMedia` INT NOT NULL AUTO_INCREMENT,
  `idMedia` INT NOT NULL,
  `idJeu` INT NOT NULL,
  PRIMARY KEY (`idJeuMedia`),
  INDEX `fk_JeuxMedia_Media1_idx` (`idMedia` ASC),
  INDEX `fk_JeuxMedia_jeu1_idx` (`idJeu` ASC),
  CONSTRAINT `fk_JeuxMedia_Media1`
    FOREIGN KEY (`idMedia`)
    REFERENCES `mydb`.`Media` (`idMedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JeuxMedia_jeu1`
    FOREIGN KEY (`idJeu`)
    REFERENCES `mydb`.`Jeu` (`idJeu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JeuTest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JeuTest` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JeuTest` (
  `idJeuTest` INT NOT NULL AUTO_INCREMENT,
  `idTest` INT NOT NULL,
  `idJeu` INT NOT NULL,
  PRIMARY KEY (`idJeuTest`),
  INDEX `fk_JeuxTest_jeu1_idx` (`idJeu` ASC),
  INDEX `fk_JeuTest_Test1_idx` (`idTest` ASC),
  CONSTRAINT `fk_JeuxTest_jeu1`
    FOREIGN KEY (`idJeu`)
    REFERENCES `mydb`.`Jeu` (`idJeu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JeuTest_Test1`
    FOREIGN KEY (`idTest`)
    REFERENCES `mydb`.`Test` (`idTest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
